/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary":                  "#00628c",
        "primary-container":        "#007cb0",
        "primary-fixed":            "#c8e6ff",
        "primary-fixed-dim":        "#88ceff",
        "on-primary":               "#ffffff",
        "on-primary-fixed":         "#001e2e",
        "on-primary-fixed-variant": "#004c6d",
        "on-primary-container":     "#fcfcff",
        "secondary":                "#4d6073",
        "secondary-container":      "#cee2f8",
        "secondary-fixed":          "#d1e5fb",
        "secondary-fixed-dim":      "#b5c9de",
        "on-secondary":             "#ffffff",
        "on-secondary-container":   "#526577",
        "on-secondary-fixed":       "#081d2d",
        "on-secondary-fixed-variant":"#36495a",
        "tertiary":                 "#00694b",
        "tertiary-container":       "#00855f",
        "tertiary-fixed":           "#7ef9c6",
        "tertiary-fixed-dim":       "#60dcab",
        "on-tertiary":              "#ffffff",
        "on-tertiary-container":    "#f5fff7",
        "on-tertiary-fixed":        "#002115",
        "on-tertiary-fixed-variant":"#005139",
        "surface":                  "#f7f9ff",
        "surface-bright":           "#f7f9ff",
        "surface-dim":              "#ccdcef",
        "surface-container-lowest": "#ffffff",
        "surface-container-low":    "#edf4ff",
        "surface-container":        "#e3efff",
        "surface-container-high":   "#daeafd",
        "surface-container-highest":"#d4e4f7",
        "surface-variant":          "#d4e4f7",
        "surface-tint":             "#006590",
        "on-surface":               "#0d1d2b",
        "on-surface-variant":       "#3e4850",
        "on-background":            "#0d1d2b",
        "background":               "#f7f9ff",
        "outline":                  "#6f7881",
        "outline-variant":          "#bec8d1",
        "inverse-surface":          "#233240",
        "inverse-on-surface":       "#e8f2ff",
        "inverse-primary":          "#88ceff",
        "error":                    "#ba1a1a",
        "error-container":          "#ffdad6",
        "on-error":                 "#ffffff",
        "on-error-container":       "#93000a",
      },
      fontFamily: {
        sans:    ['Inter', 'system-ui', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
    },
  },
  plugins: [],
}
